# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_io', '0001_initial'),
        ('rdf_io', '0003_load'),
    ]

    operations = [
    ]
