# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 23:51
from __future__ import unicode_literals

from django.db import migrations

from rdf_io.models import Namespace, ObjectType,ObjectMapping,AttributeMapping 

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
#      Namespace.objects.get_or_create( uri='http://www.w3.org/1999/02/22-rdf-syntax-ns#',
#        defaults = { 'prefix' : 'rdf' , 'notes': 'RDF' } ),
#      Namespace.objects.get_or_create( uri='http://www.w3.org/2000/01/rdf-schema#',
#        defaults = { 'prefix' : 'rdfs' , 'notes': 'RDFS' } ),
#      Namespace.objects.get_or_create( uri='http://purl.org/dc/terms/',
#        defaults = { 'prefix' : 'dct' , 'notes': 'Dublin Core Terms' } ),
#      Namespace.objects.get_or_create( uri='http://www.w3.org/ns/dcat#',
#        defaults = { 'prefix' : 'dcat' , 'notes': 'DCAT' } ),
#      Namespace.objects.get_or_create( uri='http://www.w3.org/2001/XMLSchema#',
#        defaults = { 'prefix' : 'xsd' , 'notes': 'XSD' } )
]

